---
pipeline:
  test:
    image: python:3.9.2-slim-buster
    commands:
      - apt update && apt install -y curl
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=$PATH:$HOME/.poetry/bin
      - poetry install
      - poetry run pytest --force-sugar
