---
pipeline:
  test:
    image: python:3.9.2-slim-buster
    commands:
      - apt update && apt install -y curl
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - export PATH=$PATH:$HOME/.poetry/bin
      - poetry install
      - poetry run pytest --force-sugar
