---
pipeline:
  test:
    image: python:3.11-slim-bullseye
    commands:
      - apt update && apt install -y curl
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH="/root/.local/bin:$PATH"
      - poetry install
      - poetry run pytest --force-sugar
